# Generated by Django 4.0.3 on 2022-04-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=55)),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорія',
            },
        ),
    ]
