# Generated by Django 4.0.4 on 2022-06-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('vanish', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, upload_to='static/shop/img/products')),
                ('group', models.CharField(choices=[('closes', 'Одяг'), ('tourism', 'Туризм'), ('hunt', 'Полювання'), ('shoes', 'Взуття')], default='Other', max_length=20)),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
