# Generated by Django 4.0.3 on 2022-04-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('vanish', models.BooleanField(default=False)),
                ('img', models.ImageField(default='{% static "main/img/banner04.jpg" %}', upload_to='{% static "main/img" %}')),
                ('group', models.CharField(choices=[('hunt', 'Полювання'), ('tourism', 'Туризм')], default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
