# Generated by Django 4.0.4 on 2022-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.CharField(choices=[('shoes', 'Взуття'), ('closes', 'Одяг'), ('tourism', 'Туризм'), ('hunt', 'Полювання')], default='Other', max_length=20),
        ),
    ]
