# Generated by Django 4.0.4 on 2022-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.CharField(choices=[('shoes', 'Взуття'), ('tourism', 'Туризм'), ('hunt', 'Полювання'), ('closes', 'Одяг')], default='Other', max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/shop/img/products', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='products',
            name='vanish',
            field=models.BooleanField(default=True, verbose_name='Наявність'),
        ),
    ]
