# Generated by Django 4.0.4 on 2022-06-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40, verbose_name="Ім'я")),
                ('sname', models.CharField(max_length=40, verbose_name='Прізвище')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('citi', models.CharField(choices=[('donetsk', 'Донецька'), ('vinnytsia', 'Вінницька'), ('cherkasy', 'Черкаська'), ('ternopil', 'Тернопільська'), ('zhytomyr', 'Житомирська'), ('kharkiv', 'Харківська'), ('transcarpathian', 'Закарпатська'), ('kirovohrad', 'Кіровоградська'), ('rivne', 'Рівненська'), ('dnipropetrovsk', 'Дніпропетровська'), ('zaporizhzhia', 'Запорізька'), ('khmelnytsky', 'Хмельницька'), ('volyn', 'Волинська'), ('sumy', 'Сумська'), ('lviv', 'Львівська'), ('kyiv', 'Київська'), ('chernihiv', 'Чернігівська'), ('mykolayiv', 'Миколаївська'), ('luhansk', 'Луганська'), ('ivano-frankivsk', 'Івано-Франківська'), ('poltava', 'Полтавська'), ('kherson', 'Херсонська'), ('odesa', 'Одеська'), ('crimea', 'АР Крим'), ('chernivtsi', 'Чернівецька')], max_length=40, verbose_name='Область')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
            },
        ),
    ]
