# Generated by Django 4.0.4 on 2022-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('luhansk', 'Луганська'), ('lviv', 'Львівська'), ('ternopil', 'Тернопільська'), ('poltava', 'Полтавська'), ('dnipropetrovsk', 'Дніпропетровська'), ('transcarpathian', 'Закарпатська'), ('kharkiv', 'Харківська'), ('zaporizhzhia', 'Запорізька'), ('mykolayiv', 'Миколаївська'), ('ivano-frankivsk', 'Івано-Франківська'), ('zhytomyr', 'Житомирська'), ('khmelnytsky', 'Хмельницька'), ('odesa', 'Одеська'), ('cherkasy', 'Черкаська'), ('crimea', 'АР Крим'), ('volyn', 'Волинська'), ('kyiv', 'Київська'), ('chernihiv', 'Чернігівська'), ('kherson', 'Херсонська'), ('vinnytsia', 'Вінницька'), ('rivne', 'Рівненська'), ('kirovohrad', 'Кіровоградська'), ('chernivtsi', 'Чернівецька'), ('donetsk', 'Донецька'), ('sumy', 'Сумська')], max_length=40, verbose_name='Область'),
        ),
    ]
