# Generated by Django 4.0.4 on 2022-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('ivano-frankivsk', 'Івано-Франківська'), ('lviv', 'Львівська'), ('cherkasy', 'Черкаська'), ('odesa', 'Одеська'), ('kirovohrad', 'Кіровоградська'), ('mykolayiv', 'Миколаївська'), ('luhansk', 'Луганська'), ('chernivtsi', 'Чернівецька'), ('chernihiv', 'Чернігівська'), ('kyiv', 'Київська'), ('rivne', 'Рівненська'), ('zhytomyr', 'Житомирська'), ('khmelnytsky', 'Хмельницька'), ('sumy', 'Сумська'), ('volyn', 'Волинська'), ('dnipropetrovsk', 'Дніпропетровська'), ('poltava', 'Полтавська'), ('donetsk', 'Донецька'), ('kharkiv', 'Харківська'), ('crimea', 'АР Крим'), ('vinnytsia', 'Вінницька'), ('transcarpathian', 'Закарпатська'), ('kherson', 'Херсонська'), ('ternopil', 'Тернопільська'), ('zaporizhzhia', 'Запорізька')], max_length=40, verbose_name='Область'),
        ),
    ]
