# Generated by Django 4.0.4 on 2022-06-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kirovohrad', 'Кіровоградська'), ('ternopil', 'Тернопільська'), ('crimea', 'АР Крим'), ('chernivtsi', 'Чернівецька'), ('kherson', 'Херсонська'), ('cherkasy', 'Черкаська'), ('poltava', 'Полтавська'), ('luhansk', 'Луганська'), ('volyn', 'Волинська'), ('odesa', 'Одеська'), ('kyiv', 'Київська'), ('dnipropetrovsk', 'Дніпропетровська'), ('khmelnytsky', 'Хмельницька'), ('transcarpathian', 'Закарпатська'), ('sumy', 'Сумська'), ('zhytomyr', 'Житомирська'), ('zaporizhzhia', 'Запорізька'), ('chernihiv', 'Чернігівська'), ('lviv', 'Львівська'), ('vinnytsia', 'Вінницька'), ('donetsk', 'Донецька'), ('rivne', 'Рівненська'), ('kharkiv', 'Харківська'), ('ivano-frankivsk', 'Івано-Франківська'), ('mykolayiv', 'Миколаївська')], max_length=40, verbose_name='Область'),
        ),
    ]
