# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('ternopil', 'Тернопільська'), ('rivne', 'Рівненська'), ('chernivtsi', 'Чернівецька'), ('donetsk', 'Донецька'), ('crimea', 'АР Крим'), ('volyn', 'Волинська'), ('odesa', 'Одеська'), ('cherkasy', 'Черкаська'), ('vinnytsia', 'Вінницька'), ('poltava', 'Полтавська'), ('zaporizhzhia', 'Запорізька'), ('sumy', 'Сумська'), ('chernihiv', 'Чернігівська'), ('ivano-frankivsk', 'Івано-Франківська'), ('zhytomyr', 'Житомирська'), ('transcarpathian', 'Закарпатська'), ('kirovohrad', 'Кіровоградська'), ('luhansk', 'Луганська'), ('lviv', 'Львівська'), ('mykolayiv', 'Миколаївська'), ('dnipropetrovsk', 'Дніпропетровська'), ('kharkiv', 'Харківська'), ('khmelnytsky', 'Хмельницька'), ('kherson', 'Херсонська'), ('kyiv', 'Київська')], max_length=40, verbose_name='Область'),
        ),
    ]
