# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kyiv', 'Київська'), ('odesa', 'Одеська'), ('kirovohrad', 'Кіровоградська'), ('khmelnytsky', 'Хмельницька'), ('rivne', 'Рівненська'), ('poltava', 'Полтавська'), ('ivano-frankivsk', 'Івано-Франківська'), ('luhansk', 'Луганська'), ('crimea', 'АР Крим'), ('mykolayiv', 'Миколаївська'), ('kherson', 'Херсонська'), ('transcarpathian', 'Закарпатська'), ('ternopil', 'Тернопільська'), ('cherkasy', 'Черкаська'), ('lviv', 'Львівська'), ('dnipropetrovsk', 'Дніпропетровська'), ('chernivtsi', 'Чернівецька'), ('kharkiv', 'Харківська'), ('chernihiv', 'Чернігівська'), ('vinnytsia', 'Вінницька'), ('donetsk', 'Донецька'), ('zhytomyr', 'Житомирська'), ('volyn', 'Волинська'), ('zaporizhzhia', 'Запорізька'), ('sumy', 'Сумська')], max_length=40, verbose_name='Область'),
        ),
    ]
