# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('luhansk', 'Луганська'), ('rivne', 'Рівненська'), ('zhytomyr', 'Житомирська'), ('chernivtsi', 'Чернівецька'), ('poltava', 'Полтавська'), ('cherkasy', 'Черкаська'), ('zaporizhzhia', 'Запорізька'), ('ternopil', 'Тернопільська'), ('crimea', 'АР Крим'), ('volyn', 'Волинська'), ('vinnytsia', 'Вінницька'), ('sumy', 'Сумська'), ('transcarpathian', 'Закарпатська'), ('kherson', 'Херсонська'), ('chernihiv', 'Чернігівська'), ('odesa', 'Одеська'), ('khmelnytsky', 'Хмельницька'), ('donetsk', 'Донецька'), ('kirovohrad', 'Кіровоградська'), ('kharkiv', 'Харківська'), ('ivano-frankivsk', 'Івано-Франківська'), ('lviv', 'Львівська'), ('mykolayiv', 'Миколаївська'), ('kyiv', 'Київська'), ('dnipropetrovsk', 'Дніпропетровська')], max_length=40, verbose_name='Область'),
        ),
    ]
