# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('lviv', 'Львівська'), ('kyiv', 'Київська'), ('rivne', 'Рівненська'), ('cherkasy', 'Черкаська'), ('transcarpathian', 'Закарпатська'), ('chernivtsi', 'Чернівецька'), ('volyn', 'Волинська'), ('vinnytsia', 'Вінницька'), ('kharkiv', 'Харківська'), ('dnipropetrovsk', 'Дніпропетровська'), ('kirovohrad', 'Кіровоградська'), ('kherson', 'Херсонська'), ('khmelnytsky', 'Хмельницька'), ('ivano-frankivsk', 'Івано-Франківська'), ('mykolayiv', 'Миколаївська'), ('sumy', 'Сумська'), ('luhansk', 'Луганська'), ('zhytomyr', 'Житомирська'), ('crimea', 'АР Крим'), ('chernihiv', 'Чернігівська'), ('donetsk', 'Донецька'), ('poltava', 'Полтавська'), ('ternopil', 'Тернопільська'), ('zaporizhzhia', 'Запорізька'), ('odesa', 'Одеська')], max_length=40, verbose_name='Область'),
        ),
    ]
