# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('luhansk', 'Луганська'), ('khmelnytsky', 'Хмельницька'), ('volyn', 'Волинська'), ('transcarpathian', 'Закарпатська'), ('dnipropetrovsk', 'Дніпропетровська'), ('rivne', 'Рівненська'), ('kharkiv', 'Харківська'), ('zaporizhzhia', 'Запорізька'), ('lviv', 'Львівська'), ('crimea', 'АР Крим'), ('odesa', 'Одеська'), ('sumy', 'Сумська'), ('zhytomyr', 'Житомирська'), ('ternopil', 'Тернопільська'), ('chernihiv', 'Чернігівська'), ('kyiv', 'Київська'), ('poltava', 'Полтавська'), ('kherson', 'Херсонська'), ('donetsk', 'Донецька'), ('kirovohrad', 'Кіровоградська'), ('cherkasy', 'Черкаська'), ('chernivtsi', 'Чернівецька'), ('ivano-frankivsk', 'Івано-Франківська'), ('vinnytsia', 'Вінницька'), ('mykolayiv', 'Миколаївська')], max_length=40, verbose_name='Область'),
        ),
    ]
