# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('dnipropetrovsk', 'Дніпропетровська'), ('poltava', 'Полтавська'), ('odesa', 'Одеська'), ('khmelnytsky', 'Хмельницька'), ('transcarpathian', 'Закарпатська'), ('ivano-frankivsk', 'Івано-Франківська'), ('ternopil', 'Тернопільська'), ('chernihiv', 'Чернігівська'), ('rivne', 'Рівненська'), ('luhansk', 'Луганська'), ('chernivtsi', 'Чернівецька'), ('sumy', 'Сумська'), ('volyn', 'Волинська'), ('kyiv', 'Київська'), ('kharkiv', 'Харківська'), ('kirovohrad', 'Кіровоградська'), ('vinnytsia', 'Вінницька'), ('crimea', 'АР Крим'), ('donetsk', 'Донецька'), ('lviv', 'Львівська'), ('kherson', 'Херсонська'), ('zaporizhzhia', 'Запорізька'), ('zhytomyr', 'Житомирська'), ('mykolayiv', 'Миколаївська'), ('cherkasy', 'Черкаська')], max_length=40, verbose_name='Область'),
        ),
    ]
