# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kharkiv', 'Харківська'), ('volyn', 'Волинська'), ('zaporizhzhia', 'Запорізька'), ('poltava', 'Полтавська'), ('mykolayiv', 'Миколаївська'), ('chernivtsi', 'Чернівецька'), ('vinnytsia', 'Вінницька'), ('luhansk', 'Луганська'), ('ternopil', 'Тернопільська'), ('rivne', 'Рівненська'), ('ivano-frankivsk', 'Івано-Франківська'), ('odesa', 'Одеська'), ('kirovohrad', 'Кіровоградська'), ('crimea', 'АР Крим'), ('dnipropetrovsk', 'Дніпропетровська'), ('donetsk', 'Донецька'), ('chernihiv', 'Чернігівська'), ('cherkasy', 'Черкаська'), ('lviv', 'Львівська'), ('kherson', 'Херсонська'), ('sumy', 'Сумська'), ('khmelnytsky', 'Хмельницька'), ('kyiv', 'Київська'), ('zhytomyr', 'Житомирська'), ('transcarpathian', 'Закарпатська')], max_length=40, verbose_name='Область'),
        ),
    ]
