# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('ivano-frankivsk', 'Івано-Франківська'), ('kharkiv', 'Харківська'), ('zhytomyr', 'Житомирська'), ('chernihiv', 'Чернігівська'), ('dnipropetrovsk', 'Дніпропетровська'), ('crimea', 'АР Крим'), ('kyiv', 'Київська'), ('kherson', 'Херсонська'), ('cherkasy', 'Черкаська'), ('transcarpathian', 'Закарпатська'), ('vinnytsia', 'Вінницька'), ('donetsk', 'Донецька'), ('odesa', 'Одеська'), ('lviv', 'Львівська'), ('ternopil', 'Тернопільська'), ('zaporizhzhia', 'Запорізька'), ('luhansk', 'Луганська'), ('rivne', 'Рівненська'), ('poltava', 'Полтавська'), ('mykolayiv', 'Миколаївська'), ('khmelnytsky', 'Хмельницька'), ('volyn', 'Волинська'), ('sumy', 'Сумська'), ('kirovohrad', 'Кіровоградська'), ('chernivtsi', 'Чернівецька')], max_length=40, verbose_name='Область'),
        ),
    ]
