# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('odesa', 'Одеська'), ('ternopil', 'Тернопільська'), ('chernivtsi', 'Чернівецька'), ('transcarpathian', 'Закарпатська'), ('kirovohrad', 'Кіровоградська'), ('dnipropetrovsk', 'Дніпропетровська'), ('mykolayiv', 'Миколаївська'), ('donetsk', 'Донецька'), ('kherson', 'Херсонська'), ('zhytomyr', 'Житомирська'), ('volyn', 'Волинська'), ('lviv', 'Львівська'), ('cherkasy', 'Черкаська'), ('khmelnytsky', 'Хмельницька'), ('ivano-frankivsk', 'Івано-Франківська'), ('vinnytsia', 'Вінницька'), ('rivne', 'Рівненська'), ('kharkiv', 'Харківська'), ('sumy', 'Сумська'), ('poltava', 'Полтавська'), ('crimea', 'АР Крим'), ('kyiv', 'Київська'), ('luhansk', 'Луганська'), ('chernihiv', 'Чернігівська'), ('zaporizhzhia', 'Запорізька')], max_length=40, verbose_name='Область'),
        ),
    ]
