# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('ternopil', 'Тернопільська'), ('ivano-frankivsk', 'Івано-Франківська'), ('mykolayiv', 'Миколаївська'), ('sumy', 'Сумська'), ('volyn', 'Волинська'), ('kherson', 'Херсонська'), ('poltava', 'Полтавська'), ('vinnytsia', 'Вінницька'), ('khmelnytsky', 'Хмельницька'), ('zhytomyr', 'Житомирська'), ('odesa', 'Одеська'), ('chernihiv', 'Чернігівська'), ('cherkasy', 'Черкаська'), ('kyiv', 'Київська'), ('rivne', 'Рівненська'), ('lviv', 'Львівська'), ('donetsk', 'Донецька'), ('transcarpathian', 'Закарпатська'), ('crimea', 'АР Крим'), ('dnipropetrovsk', 'Дніпропетровська'), ('kharkiv', 'Харківська'), ('luhansk', 'Луганська'), ('zaporizhzhia', 'Запорізька'), ('kirovohrad', 'Кіровоградська'), ('chernivtsi', 'Чернівецька')], max_length=40, verbose_name='Область'),
        ),
    ]
