# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('mykolayiv', 'Миколаївська'), ('poltava', 'Полтавська'), ('kirovohrad', 'Кіровоградська'), ('ternopil', 'Тернопільська'), ('donetsk', 'Донецька'), ('luhansk', 'Луганська'), ('zaporizhzhia', 'Запорізька'), ('volyn', 'Волинська'), ('ivano-frankivsk', 'Івано-Франківська'), ('zhytomyr', 'Житомирська'), ('vinnytsia', 'Вінницька'), ('chernihiv', 'Чернігівська'), ('crimea', 'АР Крим'), ('kyiv', 'Київська'), ('cherkasy', 'Черкаська'), ('sumy', 'Сумська'), ('transcarpathian', 'Закарпатська'), ('odesa', 'Одеська'), ('dnipropetrovsk', 'Дніпропетровська'), ('rivne', 'Рівненська'), ('kharkiv', 'Харківська'), ('lviv', 'Львівська'), ('chernivtsi', 'Чернівецька'), ('khmelnytsky', 'Хмельницька'), ('kherson', 'Херсонська')], max_length=40, verbose_name='Область'),
        ),
    ]
