# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('chernihiv', 'Чернігівська'), ('zhytomyr', 'Житомирська'), ('mykolayiv', 'Миколаївська'), ('vinnytsia', 'Вінницька'), ('zaporizhzhia', 'Запорізька'), ('kharkiv', 'Харківська'), ('dnipropetrovsk', 'Дніпропетровська'), ('lviv', 'Львівська'), ('rivne', 'Рівненська'), ('ternopil', 'Тернопільська'), ('odesa', 'Одеська'), ('volyn', 'Волинська'), ('kirovohrad', 'Кіровоградська'), ('chernivtsi', 'Чернівецька'), ('sumy', 'Сумська'), ('crimea', 'АР Крим'), ('khmelnytsky', 'Хмельницька'), ('luhansk', 'Луганська'), ('ivano-frankivsk', 'Івано-Франківська'), ('kherson', 'Херсонська'), ('cherkasy', 'Черкаська'), ('donetsk', 'Донецька'), ('transcarpathian', 'Закарпатська'), ('kyiv', 'Київська'), ('poltava', 'Полтавська')], max_length=40, verbose_name='Область'),
        ),
    ]
