# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('cherkasy', 'Черкаська'), ('volyn', 'Волинська'), ('luhansk', 'Луганська'), ('crimea', 'АР Крим'), ('poltava', 'Полтавська'), ('transcarpathian', 'Закарпатська'), ('donetsk', 'Донецька'), ('zhytomyr', 'Житомирська'), ('dnipropetrovsk', 'Дніпропетровська'), ('mykolayiv', 'Миколаївська'), ('sumy', 'Сумська'), ('kherson', 'Херсонська'), ('kharkiv', 'Харківська'), ('ternopil', 'Тернопільська'), ('chernivtsi', 'Чернівецька'), ('khmelnytsky', 'Хмельницька'), ('zaporizhzhia', 'Запорізька'), ('chernihiv', 'Чернігівська'), ('kirovohrad', 'Кіровоградська'), ('lviv', 'Львівська'), ('odesa', 'Одеська'), ('vinnytsia', 'Вінницька'), ('kyiv', 'Київська'), ('rivne', 'Рівненська'), ('ivano-frankivsk', 'Івано-Франківська')], max_length=40, verbose_name='Область'),
        ),
    ]
