# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('khmelnytsky', 'Хмельницька'), ('chernivtsi', 'Чернівецька'), ('mykolayiv', 'Миколаївська'), ('lviv', 'Львівська'), ('volyn', 'Волинська'), ('kherson', 'Херсонська'), ('sumy', 'Сумська'), ('donetsk', 'Донецька'), ('ternopil', 'Тернопільська'), ('kirovohrad', 'Кіровоградська'), ('chernihiv', 'Чернігівська'), ('vinnytsia', 'Вінницька'), ('rivne', 'Рівненська'), ('zhytomyr', 'Житомирська'), ('luhansk', 'Луганська'), ('poltava', 'Полтавська'), ('ivano-frankivsk', 'Івано-Франківська'), ('odesa', 'Одеська'), ('transcarpathian', 'Закарпатська'), ('crimea', 'АР Крим'), ('kyiv', 'Київська'), ('kharkiv', 'Харківська'), ('cherkasy', 'Черкаська'), ('dnipropetrovsk', 'Дніпропетровська'), ('zaporizhzhia', 'Запорізька')], max_length=40, verbose_name='Область'),
        ),
    ]
