# Generated by Django 4.0.4 on 2022-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('zaporizhzhia', 'Запорізька'), ('kharkiv', 'Харківська'), ('kherson', 'Херсонська'), ('ivano-frankivsk', 'Івано-Франківська'), ('dnipropetrovsk', 'Дніпропетровська'), ('khmelnytsky', 'Хмельницька'), ('crimea', 'АР Крим'), ('sumy', 'Сумська'), ('zhytomyr', 'Житомирська'), ('transcarpathian', 'Закарпатська'), ('ternopil', 'Тернопільська'), ('lviv', 'Львівська'), ('kyiv', 'Київська'), ('volyn', 'Волинська'), ('rivne', 'Рівненська'), ('cherkasy', 'Черкаська'), ('donetsk', 'Донецька'), ('chernivtsi', 'Чернівецька'), ('kirovohrad', 'Кіровоградська'), ('odesa', 'Одеська'), ('mykolayiv', 'Миколаївська'), ('chernihiv', 'Чернігівська'), ('poltava', 'Полтавська'), ('vinnytsia', 'Вінницька'), ('luhansk', 'Луганська')], max_length=40, verbose_name='Область'),
        ),
    ]
