# Generated by Django 4.0.4 on 2022-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('vinnytsia', 'Вінницька'), ('poltava', 'Полтавська'), ('kirovohrad', 'Кіровоградська'), ('lviv', 'Львівська'), ('rivne', 'Рівненська'), ('transcarpathian', 'Закарпатська'), ('chernihiv', 'Чернігівська'), ('khmelnytsky', 'Хмельницька'), ('kharkiv', 'Харківська'), ('chernivtsi', 'Чернівецька'), ('sumy', 'Сумська'), ('zhytomyr', 'Житомирська'), ('volyn', 'Волинська'), ('dnipropetrovsk', 'Дніпропетровська'), ('kyiv', 'Київська'), ('cherkasy', 'Черкаська'), ('odesa', 'Одеська'), ('zaporizhzhia', 'Запорізька'), ('ternopil', 'Тернопільська'), ('luhansk', 'Луганська'), ('crimea', 'АР Крим'), ('mykolayiv', 'Миколаївська'), ('ivano-frankivsk', 'Івано-Франківська'), ('kherson', 'Херсонська'), ('donetsk', 'Донецька')], max_length=40, verbose_name='Область'),
        ),
    ]
