# Generated by Django 4.0.4 on 2022-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('mykolayiv', 'Миколаївська'), ('chernivtsi', 'Чернівецька'), ('kirovohrad', 'Кіровоградська'), ('ternopil', 'Тернопільська'), ('luhansk', 'Луганська'), ('sumy', 'Сумська'), ('zaporizhzhia', 'Запорізька'), ('dnipropetrovsk', 'Дніпропетровська'), ('zhytomyr', 'Житомирська'), ('volyn', 'Волинська'), ('ivano-frankivsk', 'Івано-Франківська'), ('lviv', 'Львівська'), ('kyiv', 'Київська'), ('rivne', 'Рівненська'), ('khmelnytsky', 'Хмельницька'), ('chernihiv', 'Чернігівська'), ('kharkiv', 'Харківська'), ('odesa', 'Одеська'), ('kherson', 'Херсонська'), ('donetsk', 'Донецька'), ('transcarpathian', 'Закарпатська'), ('vinnytsia', 'Вінницька'), ('poltava', 'Полтавська'), ('cherkasy', 'Черкаська'), ('crimea', 'АР Крим')], max_length=40, verbose_name='Область'),
        ),
    ]
