# Generated by Django 4.0.4 on 2022-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('zhytomyr', 'Житомирська'), ('kirovohrad', 'Кіровоградська'), ('kherson', 'Херсонська'), ('luhansk', 'Луганська'), ('odesa', 'Одеська'), ('cherkasy', 'Черкаська'), ('crimea', 'АР Крим'), ('lviv', 'Львівська'), ('poltava', 'Полтавська'), ('transcarpathian', 'Закарпатська'), ('chernivtsi', 'Чернівецька'), ('ternopil', 'Тернопільська'), ('chernihiv', 'Чернігівська'), ('kyiv', 'Київська'), ('volyn', 'Волинська'), ('mykolayiv', 'Миколаївська'), ('zaporizhzhia', 'Запорізька'), ('dnipropetrovsk', 'Дніпропетровська'), ('donetsk', 'Донецька'), ('kharkiv', 'Харківська'), ('sumy', 'Сумська'), ('khmelnytsky', 'Хмельницька'), ('ivano-frankivsk', 'Івано-Франківська'), ('vinnytsia', 'Вінницька'), ('rivne', 'Рівненська')], max_length=40, verbose_name='Область'),
        ),
    ]
