# Generated by Django 4.0.4 on 2022-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('donetsk', 'Донецька'), ('khmelnytsky', 'Хмельницька'), ('kherson', 'Херсонська'), ('kharkiv', 'Харківська'), ('lviv', 'Львівська'), ('zaporizhzhia', 'Запорізька'), ('odesa', 'Одеська'), ('crimea', 'АР Крим'), ('dnipropetrovsk', 'Дніпропетровська'), ('zhytomyr', 'Житомирська'), ('kirovohrad', 'Кіровоградська'), ('kyiv', 'Київська'), ('ternopil', 'Тернопільська'), ('luhansk', 'Луганська'), ('rivne', 'Рівненська'), ('poltava', 'Полтавська'), ('chernihiv', 'Чернігівська'), ('transcarpathian', 'Закарпатська'), ('sumy', 'Сумська'), ('vinnytsia', 'Вінницька'), ('cherkasy', 'Черкаська'), ('ivano-frankivsk', 'Івано-Франківська'), ('chernivtsi', 'Чернівецька'), ('volyn', 'Волинська'), ('mykolayiv', 'Миколаївська')], max_length=40, verbose_name='Область'),
        ),
    ]
