# Generated by Django 4.0.4 on 2022-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('sumy', 'Сумська'), ('mykolayiv', 'Миколаївська'), ('rivne', 'Рівненська'), ('chernivtsi', 'Чернівецька'), ('cherkasy', 'Черкаська'), ('zaporizhzhia', 'Запорізька'), ('luhansk', 'Луганська'), ('kherson', 'Херсонська'), ('transcarpathian', 'Закарпатська'), ('crimea', 'АР Крим'), ('kyiv', 'Київська'), ('volyn', 'Волинська'), ('chernihiv', 'Чернігівська'), ('ternopil', 'Тернопільська'), ('odesa', 'Одеська'), ('khmelnytsky', 'Хмельницька'), ('poltava', 'Полтавська'), ('lviv', 'Львівська'), ('dnipropetrovsk', 'Дніпропетровська'), ('zhytomyr', 'Житомирська'), ('vinnytsia', 'Вінницька'), ('kharkiv', 'Харківська'), ('kirovohrad', 'Кіровоградська'), ('donetsk', 'Донецька'), ('ivano-frankivsk', 'Івано-Франківська')], max_length=40, verbose_name='Область'),
        ),
    ]
