# Generated by Django 4.0.4 on 2022-06-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('ivano-frankivsk', 'Івано-Франківська'), ('kherson', 'Херсонська'), ('crimea', 'АР Крим'), ('ternopil', 'Тернопільська'), ('dnipropetrovsk', 'Дніпропетровська'), ('chernihiv', 'Чернігівська'), ('chernivtsi', 'Чернівецька'), ('cherkasy', 'Черкаська'), ('volyn', 'Волинська'), ('mykolayiv', 'Миколаївська'), ('lviv', 'Львівська'), ('donetsk', 'Донецька'), ('rivne', 'Рівненська'), ('odesa', 'Одеська'), ('vinnytsia', 'Вінницька'), ('kirovohrad', 'Кіровоградська'), ('khmelnytsky', 'Хмельницька'), ('zhytomyr', 'Житомирська'), ('kyiv', 'Київська'), ('sumy', 'Сумська'), ('zaporizhzhia', 'Запорізька'), ('luhansk', 'Луганська'), ('kharkiv', 'Харківська'), ('transcarpathian', 'Закарпатська'), ('poltava', 'Полтавська')], max_length=40, verbose_name='Область'),
        ),
    ]
