# Generated by Django 4.0.4 on 2022-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kyiv', 'Київська'), ('kirovohrad', 'Кіровоградська'), ('cherkasy', 'Черкаська'), ('odesa', 'Одеська'), ('lviv', 'Львівська'), ('poltava', 'Полтавська'), ('crimea', 'АР Крим'), ('khmelnytsky', 'Хмельницька'), ('zaporizhzhia', 'Запорізька'), ('ternopil', 'Тернопільська'), ('volyn', 'Волинська'), ('sumy', 'Сумська'), ('mykolayiv', 'Миколаївська'), ('rivne', 'Рівненська'), ('donetsk', 'Донецька'), ('chernivtsi', 'Чернівецька'), ('kherson', 'Херсонська'), ('luhansk', 'Луганська'), ('zhytomyr', 'Житомирська'), ('ivano-frankivsk', 'Івано-Франківська'), ('kharkiv', 'Харківська'), ('chernihiv', 'Чернігівська'), ('dnipropetrovsk', 'Дніпропетровська'), ('transcarpathian', 'Закарпатська'), ('vinnytsia', 'Вінницька')], max_length=40, verbose_name='Область'),
        ),
    ]
