# Generated by Django 4.0.4 on 2022-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('vinnytsia', 'Вінницька'), ('transcarpathian', 'Закарпатська'), ('lviv', 'Львівська'), ('rivne', 'Рівненська'), ('dnipropetrovsk', 'Дніпропетровська'), ('cherkasy', 'Черкаська'), ('kharkiv', 'Харківська'), ('luhansk', 'Луганська'), ('poltava', 'Полтавська'), ('mykolayiv', 'Миколаївська'), ('kyiv', 'Київська'), ('ivano-frankivsk', 'Івано-Франківська'), ('zaporizhzhia', 'Запорізька'), ('crimea', 'АР Крим'), ('chernihiv', 'Чернігівська'), ('donetsk', 'Донецька'), ('ternopil', 'Тернопільська'), ('khmelnytsky', 'Хмельницька'), ('volyn', 'Волинська'), ('odesa', 'Одеська'), ('sumy', 'Сумська'), ('chernivtsi', 'Чернівецька'), ('zhytomyr', 'Житомирська'), ('kherson', 'Херсонська'), ('kirovohrad', 'Кіровоградська')], max_length=40, verbose_name='Область'),
        ),
    ]
