# Generated by Django 4.0.4 on 2022-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('vinnytsia', 'Вінницька'), ('kherson', 'Херсонська'), ('chernihiv', 'Чернігівська'), ('volyn', 'Волинська'), ('sumy', 'Сумська'), ('cherkasy', 'Черкаська'), ('kirovohrad', 'Кіровоградська'), ('kharkiv', 'Харківська'), ('rivne', 'Рівненська'), ('donetsk', 'Донецька'), ('transcarpathian', 'Закарпатська'), ('poltava', 'Полтавська'), ('dnipropetrovsk', 'Дніпропетровська'), ('khmelnytsky', 'Хмельницька'), ('ivano-frankivsk', 'Івано-Франківська'), ('ternopil', 'Тернопільська'), ('zhytomyr', 'Житомирська'), ('chernivtsi', 'Чернівецька'), ('crimea', 'АР Крим'), ('odesa', 'Одеська'), ('lviv', 'Львівська'), ('mykolayiv', 'Миколаївська'), ('kyiv', 'Київська'), ('luhansk', 'Луганська'), ('zaporizhzhia', 'Запорізька')], max_length=40, verbose_name='Область'),
        ),
    ]
