# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('khmelnytsky', 'Хмельницька'), ('transcarpathian', 'Закарпатська'), ('rivne', 'Рівненська'), ('chernivtsi', 'Чернівецька'), ('donetsk', 'Донецька'), ('ternopil', 'Тернопільська'), ('vinnytsia', 'Вінницька'), ('volyn', 'Волинська'), ('crimea', 'АР Крим'), ('kherson', 'Херсонська'), ('zhytomyr', 'Житомирська'), ('cherkasy', 'Черкаська'), ('kyiv', 'Київська'), ('ivano-frankivsk', 'Івано-Франківська'), ('mykolayiv', 'Миколаївська'), ('sumy', 'Сумська'), ('chernihiv', 'Чернігівська'), ('lviv', 'Львівська'), ('luhansk', 'Луганська'), ('dnipropetrovsk', 'Дніпропетровська'), ('odesa', 'Одеська'), ('zaporizhzhia', 'Запорізька'), ('poltava', 'Полтавська'), ('kharkiv', 'Харківська'), ('kirovohrad', 'Кіровоградська')], max_length=40, verbose_name='Область'),
        ),
    ]
