# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('odesa', 'Одеська'), ('chernihiv', 'Чернігівська'), ('donetsk', 'Донецька'), ('crimea', 'АР Крим'), ('poltava', 'Полтавська'), ('sumy', 'Сумська'), ('mykolayiv', 'Миколаївська'), ('chernivtsi', 'Чернівецька'), ('ternopil', 'Тернопільська'), ('dnipropetrovsk', 'Дніпропетровська'), ('zaporizhzhia', 'Запорізька'), ('kharkiv', 'Харківська'), ('ivano-frankivsk', 'Івано-Франківська'), ('transcarpathian', 'Закарпатська'), ('cherkasy', 'Черкаська'), ('kirovohrad', 'Кіровоградська'), ('kyiv', 'Київська'), ('rivne', 'Рівненська'), ('luhansk', 'Луганська'), ('lviv', 'Львівська'), ('volyn', 'Волинська'), ('zhytomyr', 'Житомирська'), ('khmelnytsky', 'Хмельницька'), ('kherson', 'Херсонська'), ('vinnytsia', 'Вінницька')], max_length=40, verbose_name='Область'),
        ),
    ]
