# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kherson', 'Херсонська'), ('chernivtsi', 'Чернівецька'), ('vinnytsia', 'Вінницька'), ('volyn', 'Волинська'), ('ternopil', 'Тернопільська'), ('zhytomyr', 'Житомирська'), ('mykolayiv', 'Миколаївська'), ('donetsk', 'Донецька'), ('crimea', 'АР Крим'), ('rivne', 'Рівненська'), ('odesa', 'Одеська'), ('sumy', 'Сумська'), ('luhansk', 'Луганська'), ('cherkasy', 'Черкаська'), ('lviv', 'Львівська'), ('khmelnytsky', 'Хмельницька'), ('zaporizhzhia', 'Запорізька'), ('chernihiv', 'Чернігівська'), ('kirovohrad', 'Кіровоградська'), ('ivano-frankivsk', 'Івано-Франківська'), ('kharkiv', 'Харківська'), ('kyiv', 'Київська'), ('transcarpathian', 'Закарпатська'), ('poltava', 'Полтавська'), ('dnipropetrovsk', 'Дніпропетровська')], max_length=40, verbose_name='Область'),
        ),
    ]
