# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('zhytomyr', 'Житомирська'), ('vinnytsia', 'Вінницька'), ('kharkiv', 'Харківська'), ('kherson', 'Херсонська'), ('odesa', 'Одеська'), ('crimea', 'АР Крим'), ('chernihiv', 'Чернігівська'), ('sumy', 'Сумська'), ('kirovohrad', 'Кіровоградська'), ('poltava', 'Полтавська'), ('khmelnytsky', 'Хмельницька'), ('ternopil', 'Тернопільська'), ('dnipropetrovsk', 'Дніпропетровська'), ('zaporizhzhia', 'Запорізька'), ('cherkasy', 'Черкаська'), ('lviv', 'Львівська'), ('mykolayiv', 'Миколаївська'), ('volyn', 'Волинська'), ('chernivtsi', 'Чернівецька'), ('luhansk', 'Луганська'), ('ivano-frankivsk', 'Івано-Франківська'), ('kyiv', 'Київська'), ('rivne', 'Рівненська'), ('transcarpathian', 'Закарпатська'), ('donetsk', 'Донецька')], max_length=40, verbose_name='Область'),
        ),
    ]
