# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kirovohrad', 'Кіровоградська'), ('ternopil', 'Тернопільська'), ('mykolayiv', 'Миколаївська'), ('rivne', 'Рівненська'), ('odesa', 'Одеська'), ('crimea', 'АР Крим'), ('kyiv', 'Київська'), ('khmelnytsky', 'Хмельницька'), ('cherkasy', 'Черкаська'), ('ivano-frankivsk', 'Івано-Франківська'), ('chernihiv', 'Чернігівська'), ('kharkiv', 'Харківська'), ('chernivtsi', 'Чернівецька'), ('donetsk', 'Донецька'), ('dnipropetrovsk', 'Дніпропетровська'), ('poltava', 'Полтавська'), ('transcarpathian', 'Закарпатська'), ('sumy', 'Сумська'), ('zhytomyr', 'Житомирська'), ('lviv', 'Львівська'), ('luhansk', 'Луганська'), ('vinnytsia', 'Вінницька'), ('zaporizhzhia', 'Запорізька'), ('volyn', 'Волинська'), ('kherson', 'Херсонська')], max_length=40, verbose_name='Область'),
        ),
    ]
