# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('lviv', 'Львівська'), ('zhytomyr', 'Житомирська'), ('dnipropetrovsk', 'Дніпропетровська'), ('kyiv', 'Київська'), ('chernivtsi', 'Чернівецька'), ('transcarpathian', 'Закарпатська'), ('cherkasy', 'Черкаська'), ('odesa', 'Одеська'), ('donetsk', 'Донецька'), ('vinnytsia', 'Вінницька'), ('rivne', 'Рівненська'), ('zaporizhzhia', 'Запорізька'), ('kirovohrad', 'Кіровоградська'), ('luhansk', 'Луганська'), ('chernihiv', 'Чернігівська'), ('khmelnytsky', 'Хмельницька'), ('kharkiv', 'Харківська'), ('sumy', 'Сумська'), ('crimea', 'АР Крим'), ('ternopil', 'Тернопільська'), ('volyn', 'Волинська'), ('kherson', 'Херсонська'), ('mykolayiv', 'Миколаївська'), ('poltava', 'Полтавська'), ('ivano-frankivsk', 'Івано-Франківська')], max_length=40, verbose_name='Область'),
        ),
    ]
