# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kyiv', 'Київська'), ('odesa', 'Одеська'), ('dnipropetrovsk', 'Дніпропетровська'), ('cherkasy', 'Черкаська'), ('zhytomyr', 'Житомирська'), ('volyn', 'Волинська'), ('ternopil', 'Тернопільська'), ('mykolayiv', 'Миколаївська'), ('kherson', 'Херсонська'), ('zaporizhzhia', 'Запорізька'), ('rivne', 'Рівненська'), ('ivano-frankivsk', 'Івано-Франківська'), ('donetsk', 'Донецька'), ('chernivtsi', 'Чернівецька'), ('lviv', 'Львівська'), ('transcarpathian', 'Закарпатська'), ('khmelnytsky', 'Хмельницька'), ('luhansk', 'Луганська'), ('kirovohrad', 'Кіровоградська'), ('chernihiv', 'Чернігівська'), ('sumy', 'Сумська'), ('kharkiv', 'Харківська'), ('vinnytsia', 'Вінницька'), ('poltava', 'Полтавська'), ('crimea', 'АР Крим')], max_length=40, verbose_name='Область'),
        ),
    ]
