# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('dnipropetrovsk', 'Дніпропетровська'), ('rivne', 'Рівненська'), ('cherkasy', 'Черкаська'), ('ivano-frankivsk', 'Івано-Франківська'), ('kirovohrad', 'Кіровоградська'), ('volyn', 'Волинська'), ('mykolayiv', 'Миколаївська'), ('poltava', 'Полтавська'), ('crimea', 'АР Крим'), ('ternopil', 'Тернопільська'), ('luhansk', 'Луганська'), ('transcarpathian', 'Закарпатська'), ('chernivtsi', 'Чернівецька'), ('chernihiv', 'Чернігівська'), ('khmelnytsky', 'Хмельницька'), ('vinnytsia', 'Вінницька'), ('zaporizhzhia', 'Запорізька'), ('sumy', 'Сумська'), ('lviv', 'Львівська'), ('kharkiv', 'Харківська'), ('odesa', 'Одеська'), ('zhytomyr', 'Житомирська'), ('donetsk', 'Донецька'), ('kherson', 'Херсонська'), ('kyiv', 'Київська')], max_length=40, verbose_name='Область'),
        ),
    ]
