# Generated by Django 4.0.4 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('kharkiv', 'Харківська'), ('khmelnytsky', 'Хмельницька'), ('kirovohrad', 'Кіровоградська'), ('donetsk', 'Донецька'), ('sumy', 'Сумська'), ('crimea', 'АР Крим'), ('poltava', 'Полтавська'), ('zaporizhzhia', 'Запорізька'), ('mykolayiv', 'Миколаївська'), ('lviv', 'Львівська'), ('odesa', 'Одеська'), ('transcarpathian', 'Закарпатська'), ('rivne', 'Рівненська'), ('ivano-frankivsk', 'Івано-Франківська'), ('kherson', 'Херсонська'), ('ternopil', 'Тернопільська'), ('cherkasy', 'Черкаська'), ('kyiv', 'Київська'), ('luhansk', 'Луганська'), ('vinnytsia', 'Вінницька'), ('volyn', 'Волинська'), ('zhytomyr', 'Житомирська'), ('dnipropetrovsk', 'Дніпропетровська'), ('chernivtsi', 'Чернівецька'), ('chernihiv', 'Чернігівська')], max_length=40, verbose_name='Область'),
        ),
    ]
