# Generated by Django 4.0.4 on 2022-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('zaporizhzhia', 'Запорізька'), ('sumy', 'Сумська'), ('lviv', 'Львівська'), ('kirovohrad', 'Кіровоградська'), ('kharkiv', 'Харківська'), ('cherkasy', 'Черкаська'), ('donetsk', 'Донецька'), ('luhansk', 'Луганська'), ('poltava', 'Полтавська'), ('kyiv', 'Київська'), ('dnipropetrovsk', 'Дніпропетровська'), ('rivne', 'Рівненська'), ('kherson', 'Херсонська'), ('zhytomyr', 'Житомирська'), ('chernivtsi', 'Чернівецька'), ('vinnytsia', 'Вінницька'), ('transcarpathian', 'Закарпатська'), ('ternopil', 'Тернопільська'), ('volyn', 'Волинська'), ('crimea', 'АР Крим'), ('chernihiv', 'Чернігівська'), ('mykolayiv', 'Миколаївська'), ('ivano-frankivsk', 'Івано-Франківська'), ('khmelnytsky', 'Хмельницька'), ('odesa', 'Одеська')], max_length=40, verbose_name='Область'),
        ),
    ]
