# Generated by Django 4.0.4 on 2022-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40, verbose_name="Ім'я")),
                ('sname', models.CharField(max_length=40, verbose_name='Прізвище')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('citi', models.CharField(choices=[('kyiv', 'Київська'), ('cherkasy', 'Черкаська'), ('odesa', 'Одеська'), ('sumy', 'Сумська'), ('vinnytsia', 'Вінницька'), ('ivano-frankivsk', 'Івано-Франківська'), ('chernivtsi', 'Чернівецька'), ('volyn', 'Волинська'), ('khmelnytsky', 'Хмельницька'), ('luhansk', 'Луганська'), ('zhytomyr', 'Житомирська'), ('transcarpathian', 'Закарпатська'), ('rivne', 'Рівненська'), ('zaporizhzhia', 'Запорізька'), ('donetsk', 'Донецька'), ('crimea', 'АР Крим'), ('dnipropetrovsk', 'Дніпропетровська'), ('kherson', 'Херсонська'), ('lviv', 'Львівська'), ('ternopil', 'Тернопільська'), ('kharkiv', 'Харківська'), ('poltava', 'Полтавська'), ('chernihiv', 'Чернігівська'), ('kirovohrad', 'Кіровоградська'), ('mykolayiv', 'Миколаївська')], max_length=40, verbose_name='Вкажіть область')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
            },
        ),
    ]
