# Generated by Django 4.0.4 on 2022-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('chernivtsi', 'Чернівецька'), ('transcarpathian', 'Закарпатська'), ('luhansk', 'Луганська'), ('cherkasy', 'Черкаська'), ('zaporizhzhia', 'Запорізька'), ('sumy', 'Сумська'), ('rivne', 'Рівненська'), ('donetsk', 'Донецька'), ('ivano-frankivsk', 'Івано-Франківська'), ('mykolayiv', 'Миколаївська'), ('zhytomyr', 'Житомирська'), ('dnipropetrovsk', 'Дніпропетровська'), ('odesa', 'Одеська'), ('ternopil', 'Тернопільська'), ('khmelnytsky', 'Хмельницька'), ('poltava', 'Полтавська'), ('lviv', 'Львівська'), ('kherson', 'Херсонська'), ('kirovohrad', 'Кіровоградська'), ('chernihiv', 'Чернігівська'), ('vinnytsia', 'Вінницька'), ('crimea', 'АР Крим'), ('kyiv', 'Київська'), ('volyn', 'Волинська'), ('kharkiv', 'Харківська')], max_length=40, verbose_name='Вкажіть область'),
        ),
    ]
