# Generated by Django 4.0.4 on 2022-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='citi',
            field=models.CharField(choices=[('zhytomyr', 'Житомирська'), ('dnipropetrovsk', 'Дніпропетровська'), ('ternopil', 'Тернопільська'), ('vinnytsia', 'Вінницька'), ('volyn', 'Волинська'), ('cherkasy', 'Черкаська'), ('kirovohrad', 'Кіровоградська'), ('chernihiv', 'Чернігівська'), ('crimea', 'АР Крим'), ('mykolayiv', 'Миколаївська'), ('odesa', 'Одеська'), ('kharkiv', 'Харківська'), ('luhansk', 'Луганська'), ('sumy', 'Сумська'), ('kyiv', 'Київська'), ('transcarpathian', 'Закарпатська'), ('zaporizhzhia', 'Запорізька'), ('lviv', 'Львівська'), ('poltava', 'Полтавська'), ('kherson', 'Херсонська'), ('rivne', 'Рівненська'), ('ivano-frankivsk', 'Івано-Франківська'), ('khmelnytsky', 'Хмельницька'), ('donetsk', 'Донецька'), ('chernivtsi', 'Чернівецька')], max_length=40, verbose_name='Вкажіть область'),
        ),
    ]
