# Generated by Django 4.0.4 on 2022-06-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.IntegerField(verbose_name='Товари')),
                ('order_price', models.IntegerField(verbose_name='Сумма')),
            ],
        ),
    ]
